import aftacImage from "./AFTAC.png";
import resumeUrl from "./Adam_Vasquez_Resume.pdf";
import pinsafeImage from "./PinSafe UI.png";
import tamuColorStackImage from "./TAMU cstack.png";
import theoImage from "./theo_logo.png";

export type SocialLinks = {
  github: string;
  linkedin: string;
  email: string;
  resume: string;
};

export type Profile = {
  name: string;
  role: string;
  location: string;
  university: string;
  degree: string;
  intro: string;
  bio: string[];
};

export type SkillGroup = {
  title: string;
  skills: string[];
};

export type Project = {
  title: string;
  description: string;
  tech: string[];
  github?: string;
  demo?: string;
  featured?: boolean;
  image: string;
  imageFit?: "cover" | "contain";
  imageAlt: string;
};

export type Experience = {
  role: string;
  company: string;
  dates: string;
  bullets: string[];
  tech: string[];
  placeholder?: boolean;
};

export type Note = {
  title: string;
  description: string;
  category: string;
  href?: string;
};

export const portfolio = {
  profile: {
    name: "Adam Vasquez",
    role: "Software Developer and Cloud Enthusiast",
    location: "Cypress, TX",
    university: "Texas A&M University",
    degree: "B.S. Computer Science",
    intro:
      "I build practical software with a growing focus on full-stack engineering, cloud infrastructure, and DevOps-minded delivery.",
    bio: [
      "I am a Computer Science student at Texas A&M University focused on software engineering, full-stack development, cloud infrastructure, and real-world technical projects.",
      "I like working across the stack, from thoughtful frontend interfaces to backend systems, deployment workflows, and infrastructure that helps software run reliably.",
      "Outside of coursework, I enjoy building projects that impact communities I am part of while deepening my understanding of AWS, DevOps practices, and production-minded engineering.",
    ],
  } satisfies Profile,
  links: {
    github: "https://github.com/Chokoadam",
    linkedin: "https://www.linkedin.com/in/adam-vasquez/",
    email: "adamv0629@tamu.edu",
    resume: resumeUrl,
  } satisfies SocialLinks,
  currently: [
    "Studying Computer Science at Texas A&M University",
    "Building full-stack projects with production-minded architecture",
    "Pursuing the AWS Certified Cloud Practitioner certification",
    "Exploring cloud infrastructure, DevOps workflows, and reliable deployment practices",
  ],
  skills: [
    {
      title: "Frontend",
      skills: ["React", "TypeScript", "JavaScript", "HTML", "CSS", "Tailwind", "Vite"],
    },
    {
      title: "Backend",
      skills: ["Python", "Java", "C/C++", "SQL", "Firebase", "REST APIs"],
    },
    {
      title: "Cloud & DevOps",
      skills: ["AWS", "Cloud Infrastructure", "DevOps", "CI/CD", "Docker", "Linux"],
    },
    {
      title: "Tools",
      skills: ["Git", "GitHub", "GitHub Actions", "Vitest", "CLI", "VS Code", "Figma"],
    },
  ] satisfies SkillGroup[],
  projects: [
    {
      title: "AFTAC HYSPLIT Visualizer",
      description:
        "CSCE Capstone Spring 2026. Web-based GIS application that enables analysts to upload, parse, and interactively visualize time-based nuclear plume dispersion data generated by the HYSPLIT atmospheric modeling system.",
      tech: ["Svelte", "TypeScript", "Leaflet", "Vitest", "Zed"],
      github: "https://github.com/SP26-CSCE482-capstone/code-documented-code-github-documentation-aftac-hysplit",
      featured: true,
      image: aftacImage,
      imageFit: "cover",
      imageAlt: "AFTAC HYSPLIT Visualizer interface preview",
    },
    {
      title: "TAMU ColorStack Website",
      description:
        "Redesign and development of the official ColorStack website for Texas A&M University, featuring a modern UI and improved user experience.",
      tech: ["React", "Vite", "TypeScript"],
      demo: "https://www.tamucolorstack.com/",
      featured: true,
      image: tamuColorStackImage,
      imageFit: "cover",
      imageAlt: "TAMU ColorStack Website interface preview",
    },
    {
      title: "Theo",
      description:
        "Teamup Software Development Internship program, Summer 2025. Full-stack tutoring marketplace web application meant to connect students with tutors in a streamlined and user-friendly way.",
      tech: ["React.js", "Vite", "Vitest", "Tailwind CSS", "Python", "Django", "Google OAuth"],
      demo: "https://theo.teamup.org/",
      featured: true,
      image: theoImage,
      imageFit: "contain",
      imageAlt: "Theo app",
    },
    {
      title: "Pinsafe",
      description:
        "TidalHack 2025. Community-powered safety intelligence platform that combines crowdsourced incident reporting, interactive geospatial mapping, and AI-driven insights to help users assess the safety of an area in real time.",
      tech: ["React", "TypeScript", "Vite", "Tailwind CSS", "Python", "FastAPI", "SQLite"],
      github: "https://github.com/jjmoy/TIDAL_HACK_2025",
      image: pinsafeImage,
      imageFit: "cover",
      imageAlt: "Pinsafe",
    },
  ] satisfies Project[],
  experience: [
    {
      // Replace this entry with internship, research, student org, or job details from your resume.
      role: "Software Development Intern",
      company: "Teamup",
      dates: "June 2025 - August 2025",
      bullets: [
        "Improved user onboarding and navigation by developing a React + Vite landing page, OAuth-aware navbar, and accounteditor, increasing feature accessibility and reducing user friction",
        "Increased frontend reliability by implementing 9 Vitest test suites for authentication and navigation flows, reducing regression-related bugs during deployment.",
        "Accelerated feature delivery by collaborating in Agile sprints, code reviews, and Git workflows, supporting on-time releases across cross-functional teams.",
      ],
      tech: ["React", "JavaScript", "Python", "Django", "Vitest", "GitHub"],
      placeholder: true,
    },
    {
      // Replace this entry with a notable project team, course, organization, or leadership role.
      role: "Secretary",
      company: "ColorStack at Texas A&M University",
      dates: "May 2025 - Present",
      bullets: [
        "Increased technical interview readiness by organizing weekly LeetRoom sessions for 10–15 members focused on algorithmic problem solving.",
        "Expanded chapter visibility by leading development of a responsive website with interactive components, boosting student engagement across 3+ pages.",
        "Strengthened community retention by coordinating 5+ professional and social events serving 40+ members.",
        "Improved sponsor outreach by compiling and distributing a 40-member resume book, enabling direct internship and recruiting connections",
      ],
      tech: ["Leadership", "Problem Solving", "Organization", "Teamwork"],
    },
  ] satisfies Experience[],
  notes: [
    {
      // Replace with blog posts, project write-ups, reading notes, or technical reflections.
      title: "Engineering Notes Placeholder",
      description:
        "A concise slot for thoughts on software design, coursework, debugging lessons, or project decisions.",
      category: "Notes",
      href: "#contact",
    },
    {
      title: "Project Retrospective Placeholder",
      description:
        "Use this space for a short case study about what you built, what changed, and what you learned.",
      category: "Writing",
      href: "#projects",
    },
    {
      title: "Learning Log Placeholder",
      description:
        "A clean home for cloud notes, DevOps workflows, books, tools, algorithms, and ideas worth revisiting.",
      category: "Learning",
      href: "#skills",
    },
  ] satisfies Note[],
  hobbies: [
    "Chess",
    "Music",
    "Competitive Mario Kart",
    "Baseball",
    "Rubik's cubes",
    "Tetris",
  ],
};
